API_ENV:
  development:
    HOST: "http://api.nytimes.com/svc/books/v2/lists/best-sellers/history.json"
    KEY: "36c07f2c2a198d74d3d5e2f8e4cbc42b:12:67895334"
  test:
    HOST: "http://api.nytimes.com/svc/books/v2/lists/best-sellers/history.json"
    KEY: "36c07f2c2a198d74d3d5e2f8e4cbc42b:12:67895334"
  production:
    HOST: "http://api.nytimes.com/svc/books/v2/lists/best-sellers/history.json"
    KEY: "36c07f2c2a198d74d3d5e2f8e4cbc42b:12:67895334"
