# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('df9ff4a633b8a9d14d54a3c2b6c0a2b2_MjUwNDExMjAxMy0wNy0xOSAwOTozODozOS4xODMxMjU')
  end)
end
